-- Copyright (C) 2023 Avant/Dr4wn | All Rights Reserved
return {
	{
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
		{pan = math.rad(0), tilt = math.rad(0)},
	}, {
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
		{tilt = math.rad(25)},
	}, {
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
		{tilt = math.rad(45)},
	}, {
		{pan = math.rad(50), tilt = math.rad(45)},
		{pan = math.rad(-50), tilt = math.rad(45)},
		{pan = math.rad(50), tilt = math.rad(45)},
		{pan = math.rad(-50), tilt = math.rad(45)},
		{pan = math.rad(50), tilt = math.rad(45)},
		{pan = math.rad(-50), tilt = math.rad(45)},
		{pan = math.rad(50), tilt = math.rad(45)},
		{pan = math.rad(-50), tilt = math.rad(45)},
		{pan = math.rad(50), tilt = math.rad(45)},
		{pan = math.rad(-50), tilt = math.rad(45)},
	}, {
		{pan = math.rad(-65)},
		{pan = math.rad(-45)},
		{pan = math.rad(-35)},
		{pan = math.rad(-25)},
		{pan = math.rad(15)},
		{pan = math.rad(15)},
		{pan = math.rad(25)},
		{pan = math.rad(35)},
		{pan = math.rad(45)},
		{pan = math.rad(65)},
	}, {
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
		{tilt = math.rad(90)},
	}, {
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
		{tilt = math.rad(-5)},
	}, {
		{pan = math.rad(90),   tilt = math.rad(45)} ,
		{pan = math.rad(90),   tilt = math.rad(45)},
		{pan = math.rad(90),   tilt = math.rad(45)},
		{pan = math.rad(90),  tilt = math.rad(45)},
		{pan = math.rad(90),  tilt = math.rad(45)},
		{pan = math.rad(-90), tilt = math.rad(45)},
		{pan = math.rad(-90), tilt = math.rad(45)},
		{pan = math.rad(-90), tilt = math.rad(45)},
		{pan = math.rad(-90), tilt = math.rad(45)},
		{pan = math.rad(-90), tilt = math.rad(45)},
	}, {
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
		{pan = math.rad(0), tilt = math.rad(90)},
	},
}